[variables]
NPM_CONFIG_INCLUDE_WORKSPACE_ROOT = "false"

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm ci --omit=dev']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'npm start'
